server:
 port: ${OPENSHIFT_DIY_PORT}

twitter4j:
 oauth:
  consumerKey: ${consumerKey}
  consumerSecret: ${consumerSecret}
  accessToken: ${accessToken}
  accessTokenSecret: ${accessTokenSecret}
  
spring:
   redis:
      host: 192.168.99.100
      port: 32768
      